export const POKEMON_TYPES_COLORS = Object.freeze({
  Normal: "bg-normal text-primary",
  Fighting: "bg-fighting text-primary",
  Flying: "bg-flying text-primary",
  Poison: "bg-poison text-secondary",
  Ground: "bg-ground text-secondary",
  Rock: "bg-rock text-primary",
  Bug: "bg-bug text-secondary",
  Ghost: "bg-ghost text-secondary",
  Steel: "bg-steel text-secondary",
  Fire: "bg-fire text-secondary",
  Water: "bg-water text-secondary",
  Grass: "bg-grass text-secondary",
  Electric: "bg-electric text-primary",
  Psychic: "bg-psychic text-secondary",
  Ice: "bg-ice text-primary",
  Dragon: "bg-dragon text-secondary",
  Dark: "bg-dark text-secondary",
  Fairy: "bg-fairy text-primary",
  Stellar: "bg-stellar text-secondary",
  Unknown: "bg-unknown text-secondary",
});
